<?php

namespace ContainerQvekhNc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CO3zX4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cO3z_X4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cO3z_X4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'htmlSanitizer' => ['privates', '.errored.4C9VtiU', NULL, 'Cannot determine controller argument for "App\\Controller\\VatController::index()": the $htmlSanitizer argument is type-hinted with the non-existent class or interface: "Symfony\\Component\\HtmlSanitizer\\HtmlSanitizerInterface".'],
        ], [
            'doctrine' => '?',
            'htmlSanitizer' => '?',
        ]);
    }
}
